blueprint:
  name: Switch - Philips Hue Dimmer Switch
  description: 'Control your home with a Philips Hue Dimmer Switch,
    for use with [ZHA](https://www.home-assistant.io/integrations/zha/).

    Version: 1.0.0

    Compatible with:
    - Philips Hue Dimmer Switch RWL022 (v2)
    Note: This is for the newer model that says "hue" on the bottom.


    All four buttons can be configured with:
    - Short press
    - Double press
    - Triple press


    Each button can be configured independently:
    - Power button: All press types
    - Up button: All press types
    - Down button: All press types
    - Hue button: All press types'
  domain: automation
  input:
    remote:
      name: Remote
      description: Philips Hue Dimmer Switch to use
      selector:
        device:
          integration: "zha"
          manufacturer: "Signify Netherlands B.V."
          model: "RWL022"
          multiple: false
    # Power button inputs
    power_press:
      name: Power button - short press
      description: Action to run on short press of power button
      default: []
      selector:
        action: {}
    power_double:
      name: Power button - double press
      description: Action to run on double press of power button
      default: []
      selector:
        action: {}
    power_triple:
      name: Power button - triple press
      description: Action to run on triple press of power button
      default: []
      selector:
        action: {}
    # Up button inputs
    up_press:
      name: Up button - short press
      description: Action to run on short press of up button
      default: []
      selector:
        action: {}
    up_double:
      name: Up button - double press
      description: Action to run on double press of up button
      default: []
      selector:
        action: {}
    up_triple:
      name: Up button - triple press
      description: Action to run on triple press of up button
      default: []
      selector:
        action: {}
    # Down button inputs
    down_press:
      name: Down button - short press
      description: Action to run on short press of down button
      default: []
      selector:
        action: {}
    down_double:
      name: Down button - double press
      description: Action to run on double press of down button
      default: []
      selector:
        action: {}
    down_triple:
      name: Down button - triple press
      description: Action to run on triple press of down button
      default: []
      selector:
        action: {}
    # Hue button inputs
    hue_press:
      name: Hue button - short press
      description: Action to run on short press of hue button
      default: []
      selector:
        action: {}
    hue_double:
      name: Hue button - double press
      description: Action to run on double press of hue button
      default: []
      selector:
        action: {}
    hue_triple:
      name: Hue button - triple press
      description: Action to run on triple press of hue button
      default: []
      selector:
        action: {}
  source_url: https://github.com/Baanaaana/ha-blueprint/tree/main

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
  - choose:
      # Power button
      - conditions: '{{ command == "on_press" }}'
        sequence: !input power_press
      - conditions: '{{ command == "on_double_press" }}'
        sequence: !input power_double
      - conditions: '{{ command == "on_triple_press" }}'
        sequence: !input power_triple

      # Up button
      - conditions: '{{ command == "up_press" }}'
        sequence: !input up_press
      - conditions: '{{ command == "up_double_press" }}'
        sequence: !input up_double
      - conditions: '{{ command == "up_triple_press" }}'
        sequence: !input up_triple

      # Down button
      - conditions: '{{ command == "down_press" }}'
        sequence: !input down_press
      - conditions: '{{ command == "down_double_press" }}'
        sequence: !input down_double
      - conditions: '{{ command == "down_triple_press" }}'
        sequence: !input down_triple

      # Hue button
      - conditions: '{{ command == "off_press" }}'
        sequence: !input hue_press
      - conditions: '{{ command == "off_double_press" }}'
        sequence: !input hue_double
      - conditions: '{{ command == "off_triple_press" }}'
        sequence: !input hue_triple
