blueprint:
  name: Switch - IKEA PARASOLL - door/window sensor
  description: 'Control your home with an IKEA PARASOLL door/window sensor,
    for use with [ZHA](https://www.home-assistant.io/integrations/zha/).

    Version: 1.0.1

    Compatible with:
    - IKEA PARASOLL door/window sensor
    - IKEA PARASOLL wireless open/close sensor (E2013)


    The sensor can trigger actions on:
    - Opening
    - Closing
    - Battery level warnings (optional)'
  domain: automation
  input:
    sensor:
      name: Sensor
      description: IKEA PARASOLL sensor to use
      selector:
        device:
          integration: "zha"
          manufacturer: "IKEA of Sweden"
          model: "PARASOLL Door/Window Sensor"
          multiple: false
    on_open:
      name: On Open
      description: Action to run when the sensor detects opening
      default: []
      selector:
        action: {}
    on_close:
      name: On Close
      description: Action to run when the sensor detects closing
      default: []
      selector:
        action: {}
    battery_warning:
      name: Battery Warning
      description: Optional - Action to run when battery is low
      default: []
      selector:
        action: {}
  source_url: https://github.com/Baanaaana/ha-blueprint/tree/main

mode: restart
max_exceeded: silent

trigger:
  # Contact sensor state changes
  - platform: state
    entity_id: binary_sensor.parasoll_contact
  # Battery level monitoring
  - platform: numeric_state
    entity_id: sensor.parasoll_battery
    attribute: battery_level
    below: 15

action:
  - choose:
      # Opening detection
      - conditions:
          - condition: state
            entity_id: binary_sensor.parasoll_contact
            state: "on"
        sequence: !input on_open
      # Closing detection
      - conditions:
          - condition: state
            entity_id: binary_sensor.parasoll_contact
            state: "off"
        sequence: !input on_close
      # Battery warning
      - conditions:
          - condition: numeric_state
            entity_id: sensor.parasoll_battery
            attribute: battery_level
            below: 15
        sequence:
          - service: notify.persistent_notification
            data:
              title: "Battery is low!"
              message: "{{ state_attr('binary_sensor.parasoll_contact', 'friendly_name') }}"