blueprint:
  name: VES-ZW-WAL-009 8-Button Wall Controller
  description: Control actions for each button press on the VES-ZW-WAL-009 8-button Z-Wave wall controller
  domain: automation
  input:
    wall_controller:
      name: Wall Controller Device
      description: Select the VES-ZW-WAL-009 wall controller device
      selector:
        device:
          filter:
            - integration: zwave_js
              model: VES-ZW-WAL-009
    
    scene_001_action:
      name: Scene 001 Action
      description: Action to run when Scene 001 button is pressed
      default: []
      selector:
        action: {}
    
    scene_002_action:
      name: Scene 002 Action
      description: Action to run when Scene 002 button is pressed
      default: []
      selector:
        action: {}
    
    scene_003_action:
      name: Scene 003 Action
      description: Action to run when Scene 003 button is pressed
      default: []
      selector:
        action: {}
    
    scene_004_action:
      name: Scene 004 Action
      description: Action to run when Scene 004 button is pressed
      default: []
      selector:
        action: {}
    
    scene_005_action:
      name: Scene 005 Action
      description: Action to run when Scene 005 button is pressed
      default: []
      selector:
        action: {}
    
    scene_006_action:
      name: Scene 006 Action
      description: Action to run when Scene 006 button is pressed
      default: []
      selector:
        action: {}
    
    scene_007_action:
      name: Scene 007 Action
      description: Action to run when Scene 007 button is pressed
      default: []
      selector:
        action: {}
    
    scene_008_action:
      name: Scene 008 Action
      description: Action to run when Scene 008 button is pressed
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "001"
      value: "KeyPressed"
    id: scene_001
  
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "002"
      value: "KeyPressed"
    id: scene_002
  
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "003"
      value: "KeyPressed"
    id: scene_003
  
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "004"
      value: "KeyPressed"
    id: scene_004
  
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "005"
      value: "KeyPressed"
    id: scene_005
  
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "006"
      value: "KeyPressed"
    id: scene_006
  
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "007"
      value: "KeyPressed"
    id: scene_007
  
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input wall_controller
      property_name: scene
      property_key_name: "008"
      value: "KeyPressed"
    id: scene_008

action:
  - choose:
      - conditions:
          - condition: trigger
            id: scene_001
        sequence: !input scene_001_action
      
      - conditions:
          - condition: trigger
            id: scene_002
        sequence: !input scene_002_action
      
      - conditions:
          - condition: trigger
            id: scene_003
        sequence: !input scene_003_action
      
      - conditions:
          - condition: trigger
            id: scene_004
        sequence: !input scene_004_action
      
      - conditions:
          - condition: trigger
            id: scene_005
        sequence: !input scene_005_action
      
      - conditions:
          - condition: trigger
            id: scene_006
        sequence: !input scene_006_action
      
      - conditions:
          - condition: trigger
            id: scene_007
        sequence: !input scene_007_action
      
      - conditions:
          - condition: trigger
            id: scene_008
        sequence: !input scene_008_action

mode: parallel
max: 8