blueprint:
  name: Switch - IKEA RODRET - two button remote
  description: 'Control your home with an IKEA RODRET dimmer,
    for use with [ZHA](https://www.home-assistant.io/integrations/zha/).


    Compatible with:
    - IKEA RODRET Dimmer
    - IKEA RODRET wireless dimmer/power switch (E2201)


    Both buttons can be configured with short press,
    double press, long press and release after long press actions.


    Each button can be configured independently:
    - Top button: Short press, double press, long press and release
    - Bottom button: Short press, double press, long press and release'
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA RODRET remote to use
      selector:
        device:
          integration: "zha"
          manufacturer: "IKEA of Sweden"
          model: "RODRET Dimmer"
          multiple: false
    top_short:
      name: Top button - short press
      description: Action to run on short press of top button
      default: []
      selector:
        action: {}
    top_double:
      name: Top button - double press
      description: Action to run on double press of top button
      default: []
      selector:
        action: {}
    top_long:
      name: Top button - long press
      description: Action to run on long press of top button
      default: []
      selector:
        action: {}
    top_release:
      name: Top button - release after long press
      description: Action to run when releasing after long press of top button
      default: []
      selector:
        action: {}
    bottom_short:
      name: Bottom button - short press
      description: Action to run on short press of bottom button
      default: []
      selector:
        action: {}
    bottom_double:
      name: Bottom button - double press
      description: Action to run on double press of bottom button
      default: []
      selector:
        action: {}
    bottom_long:
      name: Bottom button - long press
      description: Action to run on long press of bottom button
      default: []
      selector:
        action: {}
    bottom_release:
      name: Bottom button - release after long press
      description: Action to run when releasing after long press of bottom button
      default: []
      selector:
        action: {}
  source_url: https://github.com/Baanaaana/ha-blueprint/tree/main
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
      - conditions:
          - "{{ command == 'short_release' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input top_short
      - conditions:
          - "{{ command == 'multi_press_complete' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input top_double
      - conditions:
          - "{{ command == 'long_press' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input top_long
      - conditions:
          - "{{ command == 'long_release' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input top_release
      - conditions:
          - "{{ command == 'short_release' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input bottom_short
      - conditions:
          - "{{ command == 'multi_press_complete' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input bottom_double
      - conditions:
          - "{{ command == 'long_press' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input bottom_long
      - conditions:
          - "{{ command == 'long_release' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input bottom_release 