blueprint:
  name: Switch - IKEA SOMRIG - two button remote
  description: 'Control your home with an IKEA SOMRIG shortcut button,
    for use with [ZHA](https://www.home-assistant.io/integrations/zha/).

    Version: 1.0.0

    Compatible with:
    - IKEA SOMRIG shortcut button
    - IKEA SOMRIG shortcut button (E2213)


    Both buttons (single dot and double dot) can be configured with short press,
    double press, long press and release after long press actions.


    Each button can be configured independently:
    - Single dot button: Short press, double press, long press and release
    - Double dot button: Short press, double press, long press and release'
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA SOMRIG remote to use
      selector:
        device:
          integration: "zha"
          manufacturer: "IKEA of Sweden"
          model: "SOMRIG shortcut button"
          multiple: false
    single_dot_short:
      name: Single dot - short press
      description: Action to run on short press of single dot button
      default: []
      selector:
        action: {}
    single_dot_double:
      name: Single dot - double press
      description: Action to run on double press of single dot button
      default: []
      selector:
        action: {}
    single_dot_long:
      name: Single dot - long press
      description: Action to run on long press of single dot button
      default: []
      selector:
        action: {}
    single_dot_release:
      name: Single dot - release after long press
      description: Action to run when releasing after long press of single dot button
      default: []
      selector:
        action: {}
    double_dot_short:
      name: Double dot - short press
      description: Action to run on short press of double dot button
      default: []
      selector:
        action: {}
    double_dot_double:
      name: Double dot - double press
      description: Action to run on double press of double dot button
      default: []
      selector:
        action: {}
    double_dot_long:
      name: Double dot - long press
      description: Action to run on long press of double dot button
      default: []
      selector:
        action: {}
    double_dot_release:
      name: Double dot - release after long press
      description: Action to run when releasing after long press of double dot button
      default: []
      selector:
        action: {}
    battery_warning:
      name: Battery Warning
      description: Optional - Action to run when battery is low
      default: []
      selector:
        action: {}
  source_url: https://github.com/Baanaaana/ha-blueprint/tree/main
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
  # Add battery monitoring
  - platform: numeric_state
    entity_id: sensor.somrig_battery
    attribute: battery_level
    below: 15

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
      # Single dot button actions
      - conditions:  # Short press
          - "{{ command == 'short_release' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input single_dot_short

      - conditions:  # Double press
          - "{{ command == 'multi_press_complete' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input single_dot_double

      - conditions:  # Long press
          - "{{ command == 'long_press' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input single_dot_long

      - conditions:  # Release after long press
          - "{{ command == 'long_release' }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input single_dot_release


      # Double dot button actions
      - conditions:  # Short press
          - "{{ command == 'short_release' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input double_dot_short

      - conditions:  # Double press
          - "{{ command == 'multi_press_complete' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input double_dot_double

      - conditions:  # Long press
          - "{{ command == 'long_press' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input double_dot_long

      - conditions:  # Release after long press
          - "{{ command == 'long_release' }}"
          - "{{ endpoint_id == 2 }}"
        sequence: !input double_dot_release


      # Battery warning
      - conditions:
          - condition: numeric_state
            entity_id: sensor.somrig_battery
            attribute: battery_level
            below: 15
        sequence: !input battery_warning